spring.application.name=ClipzConnect
spring.datasource.url=jdbc:postgresql://ep-fancy-dawn-ahsb1sp2-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_VUO6ungv5Cwq&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
